"""
Generates hotel entities and pre-computes availability calendars.

Hotels are placed at Location entities of type HOTEL that were already
generated by GeoGenerator (Pass 2). This generator enriches them with
availability data and does not create new Location objects.
"""
import math
import random
from datetime import date, timedelta

from travel_world.core.enums import LocationType
from travel_world.layers.base import LayerMeta
from travel_world.layers.accommodation_layer import AccommodationLayer, AvailabilitySlot


class AccommodationGenerator:
    """
    Generates AccommodationLayer: hotel availability calendars with demand-driven pricing.

    Availability model:
        Base occupancy depends on hotel popularity and city tourism_density.
        Seasonal modifiers are applied using a sinusoidal curve per calendar month.
        Events (from EventLayer, if available) spike demand on surrounding dates.

    Note: This generator does not create new Hotel Location objects; it reads
    hotels already generated by GeoGenerator and builds availability data on top.
    """

    def __init__(self, seed: int, config: dict):
        self.rng = random.Random(seed)
        self.config = config

    def generate(
        self,
        world_id: str,
        meta: LayerMeta,
        geo_layer,
        economics_layer=None,
    ) -> AccommodationLayer:
        """Generate availability calendars for all hotels in geo_layer."""
        hotels = {
            loc_id: loc
            for loc_id, loc in geo_layer.locations.items()
            if loc.location_type == LocationType.HOTEL
        }
        start = date.today()
        days = self.config.get("date_range_days", 90)
        all_dates = [(start + timedelta(days=i)).isoformat() for i in range(days)]
        availability: dict = {}
        for hotel_id, hotel in hotels.items():
            availability[hotel_id] = self._generate_availability(
                hotel, all_dates, economics_layer
            )
        return AccommodationLayer(meta, hotels, availability)

    def _generate_availability(self, hotel, dates: list[str], economics_layer) -> dict:
        """Generate per-date availability slots for a single hotel."""
        slots: dict = {}
        for date_str in dates:
            base_occupancy = hotel.popularity_score * 0.4
            month = date.fromisoformat(date_str).month
            seasonal = 1.0 + 0.2 * abs(math.sin(math.pi * month / 6))
            occupancy = min(0.65, base_occupancy * seasonal + self.rng.gauss(0, 0.05))
            rooms_available = max(
                3, hotel.total_rooms - int(occupancy * hotel.total_rooms)
            )
            demand = (
                economics_layer.get_hotel_demand_factor(hotel.location_id, date_str)
                if economics_layer
                else 1.0
            )
            price = hotel.price_per_night * demand
            slots[date_str] = AvailabilitySlot(
                date_str=date_str,
                rooms_available=rooms_available,
                price_tonight=round(max(1.0, price), 2),
            )
        return slots
